if(NOT ARMADILLO_ROOT STREQUAL "")
  SET(ENABLE_ARMADILLO ON)

  SET(ARMADILLO_INCLUDE_DIR ${ARMADILLO_ROOT}/include ${ARMADILLO_ROOT}/../SuperLU_4.3/SRC)
  SET(ARMADILLO_LIBRARY_DIR ${ARMADILLO_ROOT}/lib)
  SET(ARMADILLO_WRAPPER_SRC ${ARMADILLO_ROOT}/src/wrapper.cpp)
  SET(ARMADILLO_LIBRARIES blas_win64_MT lapack_win64_MT SuperLU_Lib)
endif()