if(${EXL_BUILD_OGL})

set(EXL_SUBMODULE_PROJECTS ${EXL_SUBMODULE_PROJECTS} ${EXL_ROOT}/modules/freetype)
set(EXL_SUBMODULE_TARGETS ${EXL_SUBMODULE_TARGETS} ${OUT_DIR}/modules/freetype)

SET(FREETYPE_INCLUDE_DIR ${FREETYPE_ROOT}/include)

endif()