
if(${EXL_BUILD_WITH_FREEIMAGE})
  set(EXL_SUBMODULE_PROJECTS ${EXL_SUBMODULE_PROJECTS} ${EXL_ROOT}/config/freeimage)
  set(EXL_SUBMODULE_TARGETS ${EXL_SUBMODULE_TARGETS} ${OUT_DIR}/modules/freeimage)
  SET(ENABLE_FREEIMAGE ON)
  SET(FREEIMAGE_INCLUDE_DIR ${FREEIMAGE_ROOT}/Source)
  SET(FREEIMAGE_LIBRARIES FreeImage)
  SET(FREEIMAGE_DEFINES -DFREEIMAGE_LIB)

  set(EXL_COMPILER_DEFINITIONS ${EXL_COMPILER_DEFINITIONS} -DEXL_IMAGESTREAMER_ENABLED)
endif()