SET(SDL_INCLUDE_DIR ${SDL_ROOT}/include)
SET(SDL_LIBRARY_DIR ${SDL_ROOT}/include)
set(EXL_SUBMODULE_PROJECTS ${EXL_SUBMODULE_PROJECTS} ${SDL_ROOT})
set(EXL_SUBMODULE_TARGETS ${EXL_SUBMODULE_TARGETS} ${OUT_DIR}/modules/sdl)