set(ASSIMP_ROOT ${EXL_ROOT}/modules/assimp)

set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_SHARED_LIBS ${EXL_BUILD_SHARED_LIBS} CACHE BOOL "" FORCE)

set(EXL_SUBMODULE_PROJECTS ${EXL_SUBMODULE_PROJECTS} ${EXL_ROOT}/modules/assimp)
set(EXL_SUBMODULE_TARGETS ${EXL_SUBMODULE_TARGETS} ${OUT_DIR}/modules/assimp)

set(ASSIMP_INCLUDE_DIR ${ASSIMP_ROOT}/include)
