set(GLEW_ROOT "${EXL_ROOT}/package/glew/glew-2.2.0")
SET(GLEW_INCLUDE_DIR ${GLEW_ROOT}/include)
SET(GLEW_VARIANT "Release/x64")
SET(GLEW_DEFINES )

if(${MSVC})
if(${EXL_BUILD_SHARED})
SET(GLEW_LIBRARY ${GLEW_ROOT}/lib/${GLEW_VARIANT}/glew32.lib)
else()
SET(GLEW_LIBRARY ${GLEW_ROOT}/lib/${GLEW_VARIANT}/glew32s.lib)
SET(GLEW_DEFINES ${GLEW_DEFINES} -DGLEW_STATIC)
endif()
endif()

add_subdirectory(config/glew)
set_target_properties(glew PROPERTIES FOLDER Dependencies)